idle_bg = "#181616"
idle_fg = "#c5c9c5"
info_fg = "#8ba4b0"
info_bg = "#181616"
good_fg = "#8a9a7b"
good_bg = "#181616"
warning_fg = "#c0a36e"
warning_bg = "#181616"
critical_fg = "#c4746e"
critical_bg = "#181616"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
