idle_bg = "#1a1b26"
idle_fg = "#c0caf5"
info_fg = "#16161e"
info_bg = "#0db9d7"
good_fg = "#16161e"
good_bg = "#9ece6a"
warning_fg = "#16161e"
warning_bg = "#e0af68"
critical_fg = "#16161e"
critical_bg = "#f7768e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
