return {
	-- {
	-- 	{
	-- 		"folke/flash.nvim",
	-- 		event = "VeryLazy",
	-- 		---@type Flash.Config
	-- 		opts = {
	-- 			modes = {
	-- 				search = {
	-- 					enabled = true,
	-- 				},
	-- 				char = {
	-- 					jump_labels = true,
	-- 				},
	-- 			},
	-- 		},
	--    -- stylua: ignore
	--            keys = {
	--              { "/", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Jump (Flash)" },
	--                {"<leader>/t", mode = {"n", "x", "o"}, function() require("flash").treesitter() end, desc = "Treesitter (Flash)"},
	--                {"<leader>/r", mode = {"n", "x", "o"}, function() require("flash").remote() end, desc = "Remote (Flash)"},
	--                {"<leader>/s", mode = { "x", "o"}, function() require("flash").treesitter_search() end, desc = "Treesitter Search (Flash)"},
	--                {"<c-f>", mode = {"c"}, function() require("flash").toggle() end, desc = "Toggle Flash Search"},
	--            },
	-- 	},
	-- },
	-- Minimal configuration
	-- {
	-- 	"David-Kunz/gen.nvim",
	-- 	config = function()
	-- 		require("gen").setup({
	-- 			show_model = true,
	-- 			display_mode = "vertical-split",
	-- 			show_prompt = true,
	-- 		})
	-- 		vim.keymap.set({ "n", "v" }, "<leader>gc", ":Gen Chat<CR>", { desc = "start Gen Chat" })
	-- 		vim.keymap.set({ "n", "v" }, "<leader>ga", ":Gen Ask<CR>", { desc = "Ask Gen" })
	-- 		vim.keymap.set({ "n", "v" }, "<leader>gm", ":Gen<CR>", { desc = "Gen Menu" })
	-- 	end,
	-- },
}
