#!/usr/bin/env bash

HEADPHONE_JACK="alsa_output.pci-0000_12_00.6.analog-stereo"
USB_SPEAKER="alsa_output.usb-Generic_USB2.0_Device_20170726905923-00.analog-stereo"

sel_sink() {
    local sink=$1
    pactl set-default-sink "$sink"
}

ARGS=$1

case "$ARGS" in
headphones)
    sel_sink "$HEADPHONE_JACK" >/dev/null 2>&1
    ;;

*)
    sel_sink "$USB_SPEAKER" >/dev/null 2>&1
    ;;
esac
