#!/usr/bin/env bash

STYLIX_DIR="$HOME/.config/stylix/palette.json"

BASE16=(
"base00"
"base01"
"base02"
"base03"
"base04"
"base05"
"base06"
"base07"
"base08"
"base09"
"base0A"
"base0B"
"base0C"
"base0D"
"base0E"
"base0F"
)


c_t() { local header_color="$1"
    local header="$2"

    a_r=$((16#${header_color:1:2}))
    a_g=$((16#${header_color:3:2}))
    a_b=$((16#${header_color:5:2}))

    echo -e "\e[38;2;${a_r};${a_g};${a_b}m${header}\e[0m"
}

heading="Theme: $(jq -r .scheme "$STYLIX_DIR")"

printf "%s\n" "$heading"

for item in "${BASE16[@]}"; do
  hex=$(jq -r ."$item" "$STYLIX_DIR")
  printf "%s %s %s\n" "$item" "$hex" "$(c_t "#$hex" "")"
done
