#!/usr/bin/env bash

find_dirs() {

    find "$HOME/coding/" -mindepth 1 -maxdepth 3 -type d \( \
        -name ".venv" -o -name "__pycache__" -o -name ".git" -o -name ".gitignore" -o -name "target" -o -name "release" -o -name "node_modules" \
        \) -prune -o -type d -print
}

main() {
    directories=$(find_dirs)

    sel_dir=$(echo "$directories" 2>/dev/null | fzf \
        --reverse --highlight-line --border='double' \
        --border-label='New Project' --border-label-pos=2 \
        --preview='eza --tree --color=always --icons {} ' \
        --preview-window='right' --preview-border='double' 2>/dev/null)

    if [[ "$sel_dir" == "" ]]; then
        exit
    fi

    name="$(basename "$sel_dir")"
    if ! tmux has-session -t "${name}:" 2>/dev/null; then
      tmux new-session -d -s "$name" -c "$sel_dir" "$SHELL" 2>/dev/null || {
        echo "failed to create session $name" >&2
        exit 1
      }
    fi
    if [ -n "$TMUX" ]; then
      tmux switch-client -t "$name"
    else
      tmux attach -t "$name"
    fi
}

main
